// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

package game

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StartRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Character            int32    `protobuf:"varint,2,opt,name=character,proto3" json:"character,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartRequest) Reset()         { *m = StartRequest{} }
func (m *StartRequest) String() string { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()    {}
func (*StartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0}
}

func (m *StartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRequest.Unmarshal(m, b)
}
func (m *StartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRequest.Marshal(b, m, deterministic)
}
func (m *StartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRequest.Merge(m, src)
}
func (m *StartRequest) XXX_Size() int {
	return xxx_messageInfo_StartRequest.Size(m)
}
func (m *StartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartRequest proto.InternalMessageInfo

func (m *StartRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *StartRequest) GetCharacter() int32 {
	if m != nil {
		return m.Character
	}
	return 0
}

type StartResponse struct {
	InitStatus           *Status  `protobuf:"bytes,1,opt,name=init_status,json=initStatus,proto3" json:"init_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartResponse) Reset()         { *m = StartResponse{} }
func (m *StartResponse) String() string { return proto.CompactTextString(m) }
func (*StartResponse) ProtoMessage()    {}
func (*StartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{1}
}

func (m *StartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartResponse.Unmarshal(m, b)
}
func (m *StartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartResponse.Marshal(b, m, deterministic)
}
func (m *StartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartResponse.Merge(m, src)
}
func (m *StartResponse) XXX_Size() int {
	return xxx_messageInfo_StartResponse.Size(m)
}
func (m *StartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartResponse proto.InternalMessageInfo

func (m *StartResponse) GetInitStatus() *Status {
	if m != nil {
		return m.InitStatus
	}
	return nil
}

type Actions struct {
	Action               string   `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Actions) Reset()         { *m = Actions{} }
func (m *Actions) String() string { return proto.CompactTextString(m) }
func (*Actions) ProtoMessage()    {}
func (*Actions) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{2}
}

func (m *Actions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Actions.Unmarshal(m, b)
}
func (m *Actions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Actions.Marshal(b, m, deterministic)
}
func (m *Actions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Actions.Merge(m, src)
}
func (m *Actions) XXX_Size() int {
	return xxx_messageInfo_Actions.Size(m)
}
func (m *Actions) XXX_DiscardUnknown() {
	xxx_messageInfo_Actions.DiscardUnknown(m)
}

var xxx_messageInfo_Actions proto.InternalMessageInfo

func (m *Actions) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

type Player struct {
	Sprite               int32    `protobuf:"varint,1,opt,name=sprite,proto3" json:"sprite,omitempty"`
	PosX                 int32    `protobuf:"varint,2,opt,name=posX,proto3" json:"posX,omitempty"`
	PosY                 int32    `protobuf:"varint,3,opt,name=posY,proto3" json:"posY,omitempty"`
	Health               int32    `protobuf:"varint,4,opt,name=health,proto3" json:"health,omitempty"`
	Character            int32    `protobuf:"varint,5,opt,name=character,proto3" json:"character,omitempty"`
	Username             string   `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{3}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetSprite() int32 {
	if m != nil {
		return m.Sprite
	}
	return 0
}

func (m *Player) GetPosX() int32 {
	if m != nil {
		return m.PosX
	}
	return 0
}

func (m *Player) GetPosY() int32 {
	if m != nil {
		return m.PosY
	}
	return 0
}

func (m *Player) GetHealth() int32 {
	if m != nil {
		return m.Health
	}
	return 0
}

func (m *Player) GetCharacter() int32 {
	if m != nil {
		return m.Character
	}
	return 0
}

func (m *Player) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type Status struct {
	Player1              *Player  `protobuf:"bytes,1,opt,name=player1,proto3" json:"player1,omitempty"`
	Player2              *Player  `protobuf:"bytes,2,opt,name=player2,proto3" json:"player2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{4}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetPlayer1() *Player {
	if m != nil {
		return m.Player1
	}
	return nil
}

func (m *Status) GetPlayer2() *Player {
	if m != nil {
		return m.Player2
	}
	return nil
}

func init() {
	proto.RegisterType((*StartRequest)(nil), "fightinggame.StartRequest")
	proto.RegisterType((*StartResponse)(nil), "fightinggame.StartResponse")
	proto.RegisterType((*Actions)(nil), "fightinggame.Actions")
	proto.RegisterType((*Player)(nil), "fightinggame.Player")
	proto.RegisterType((*Status)(nil), "fightinggame.Status")
}

func init() {
	proto.RegisterFile("game.proto", fileDescriptor_38fc58335341d769)
}

var fileDescriptor_38fc58335341d769 = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x31, 0x4f, 0xf3, 0x30,
	0x10, 0xad, 0xbf, 0xaf, 0x4d, 0xe9, 0xb5, 0x2c, 0x16, 0xa0, 0x28, 0x30, 0x14, 0x4f, 0x9d, 0x22,
	0x08, 0x62, 0x60, 0x64, 0x09, 0x8c, 0xc8, 0x5d, 0xe8, 0x84, 0x4c, 0x64, 0x12, 0x4b, 0x6d, 0x12,
	0xec, 0xcb, 0xc0, 0xcf, 0x60, 0xe5, 0xd7, 0xa2, 0xd8, 0x26, 0x25, 0x10, 0x89, 0xed, 0xde, 0xf9,
	0xdd, 0xe5, 0xbd, 0x7b, 0x01, 0xc8, 0xc5, 0x4e, 0xc6, 0xb5, 0xae, 0xb0, 0xa2, 0x8b, 0x17, 0x95,
	0x17, 0xa8, 0xca, 0xbc, 0xed, 0xb1, 0x7b, 0x58, 0xac, 0x51, 0x68, 0xe4, 0xf2, 0xb5, 0x91, 0x06,
	0x69, 0x04, 0x07, 0x8d, 0x91, 0xba, 0x14, 0x3b, 0x19, 0x92, 0x25, 0x59, 0xcd, 0x78, 0x87, 0xe9,
	0x19, 0xcc, 0xb2, 0x42, 0x68, 0x91, 0xa1, 0xd4, 0xe1, 0xbf, 0x25, 0x59, 0x4d, 0xf8, 0xbe, 0xc1,
	0x52, 0x38, 0xf4, 0x9b, 0x4c, 0x5d, 0x95, 0x46, 0xd2, 0x6b, 0x98, 0xab, 0x52, 0xe1, 0x93, 0x41,
	0x81, 0x8d, 0xb1, 0xdb, 0xe6, 0xc9, 0x51, 0xfc, 0xfd, 0xf3, 0xf1, 0xda, 0xbe, 0x71, 0x68, 0x89,
	0xae, 0x66, 0xe7, 0x30, 0xbd, 0xcd, 0x50, 0x55, 0xa5, 0xa1, 0x27, 0x10, 0x08, 0x5b, 0x7a, 0x29,
	0x1e, 0xb1, 0x0f, 0x02, 0xc1, 0xc3, 0x56, 0xbc, 0x49, 0xdd, 0x52, 0x4c, 0xad, 0x15, 0x3a, 0xb5,
	0x13, 0xee, 0x11, 0xa5, 0x30, 0xae, 0x2b, 0xf3, 0xe8, 0x65, 0xda, 0xda, 0xf7, 0x36, 0xe1, 0xff,
	0xae, 0xb7, 0x69, 0xe7, 0x0b, 0x29, 0xb6, 0x58, 0x84, 0x63, 0x37, 0xef, 0x50, 0xdf, 0xeb, 0xe4,
	0x87, 0xd7, 0xde, 0x95, 0x82, 0xfe, 0x95, 0x58, 0x01, 0x81, 0x73, 0x42, 0x63, 0x98, 0xd6, 0x56,
	0xe5, 0xe5, 0xb0, 0x79, 0x67, 0x81, 0x7f, 0x91, 0xf6, 0xfc, 0xc4, 0xca, 0xfe, 0x83, 0x9f, 0x24,
	0xef, 0x04, 0x16, 0xa9, 0x27, 0xdc, 0xb5, 0x01, 0xa5, 0x30, 0xb3, 0x11, 0x58, 0x10, 0xfd, 0xba,
	0x74, 0x97, 0x72, 0x74, 0x3a, 0xf8, 0xe6, 0x72, 0x63, 0x23, 0x7a, 0x03, 0x63, 0xbb, 0xe2, 0xb8,
	0x4f, 0xf3, 0xb1, 0x44, 0x83, 0x19, 0xb2, 0xd1, 0x8a, 0x5c, 0x90, 0xe7, 0xc0, 0xfe, 0x64, 0x57,
	0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0b, 0xe2, 0x56, 0xa6, 0x72, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FightingGameClient is the client API for FightingGame service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FightingGameClient interface {
	// start game
	StartGame(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	// game actions
	Game(ctx context.Context, opts ...grpc.CallOption) (FightingGame_GameClient, error)
}

type fightingGameClient struct {
	cc grpc.ClientConnInterface
}

func NewFightingGameClient(cc grpc.ClientConnInterface) FightingGameClient {
	return &fightingGameClient{cc}
}

func (c *fightingGameClient) StartGame(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, "/fightinggame.FightingGame/StartGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fightingGameClient) Game(ctx context.Context, opts ...grpc.CallOption) (FightingGame_GameClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FightingGame_serviceDesc.Streams[0], "/fightinggame.FightingGame/Game", opts...)
	if err != nil {
		return nil, err
	}
	x := &fightingGameGameClient{stream}
	return x, nil
}

type FightingGame_GameClient interface {
	Send(*Actions) error
	Recv() (*Status, error)
	grpc.ClientStream
}

type fightingGameGameClient struct {
	grpc.ClientStream
}

func (x *fightingGameGameClient) Send(m *Actions) error {
	return x.ClientStream.SendMsg(m)
}

func (x *fightingGameGameClient) Recv() (*Status, error) {
	m := new(Status)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FightingGameServer is the server API for FightingGame service.
type FightingGameServer interface {
	// start game
	StartGame(context.Context, *StartRequest) (*StartResponse, error)
	// game actions
	Game(FightingGame_GameServer) error
}

// UnimplementedFightingGameServer can be embedded to have forward compatible implementations.
type UnimplementedFightingGameServer struct {
}

func (*UnimplementedFightingGameServer) StartGame(ctx context.Context, req *StartRequest) (*StartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartGame not implemented")
}
func (*UnimplementedFightingGameServer) Game(srv FightingGame_GameServer) error {
	return status.Errorf(codes.Unimplemented, "method Game not implemented")
}

func RegisterFightingGameServer(s *grpc.Server, srv FightingGameServer) {
	s.RegisterService(&_FightingGame_serviceDesc, srv)
}

func _FightingGame_StartGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FightingGameServer).StartGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fightinggame.FightingGame/StartGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FightingGameServer).StartGame(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FightingGame_Game_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FightingGameServer).Game(&fightingGameGameServer{stream})
}

type FightingGame_GameServer interface {
	Send(*Status) error
	Recv() (*Actions, error)
	grpc.ServerStream
}

type fightingGameGameServer struct {
	grpc.ServerStream
}

func (x *fightingGameGameServer) Send(m *Status) error {
	return x.ServerStream.SendMsg(m)
}

func (x *fightingGameGameServer) Recv() (*Actions, error) {
	m := new(Actions)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _FightingGame_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fightinggame.FightingGame",
	HandlerType: (*FightingGameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartGame",
			Handler:    _FightingGame_StartGame_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Game",
			Handler:       _FightingGame_Game_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "game.proto",
}
